server {
    listen 80;
    server_name sample02.dev;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name sample02.dev;

    root /var/www/api/public;
    index index.php index.html;

    ssl_certificate /etc/nginx/ssl/sample02.dev.crt;
    ssl_certificate_key /etc/nginx/ssl/sample02.dev.key;

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        fastcgi_param HTTP_AUTHORIZATION $http_authorization;
        internal;
    }

    location ~ /\. {
        deny all;
    }
}
